# What host/post to listen on for HTTP.
listen_address=:8001

# Where the CRG Scoreboard is that we should connect to. If this is not given,
# then we must have another proxy push to us.
scoreboard_address=localhost:8000

# If given, then serve static content from this directory rather than proxying
# from scoreboard_address. A CRG Scoreboard's "html" directory would be one
# possibility for this setting. It is not safe to use the current directory,
# as contains secrets. Subdirectories are fine.
#html_directory=./html

# If given, push WS updates to this proxy.
#push_address=localhost:8002
