# What host/post to listen on for HTTP.
listen_address=:8002

# Domain name that we're serving under. A wildcard DNS entry should be setup
# for all subdomains.
domain=derbystats.eu
# Do users use HTTPS to talk to us.
domain_https=yes

# What to serve up on subdomains. It is unsafe to use the current directory.
subdomain_html_directory=./html

# Keys not to show to users. This is a mix of reducing noise, and
filter_keys=ScoreBoard\.Clients\.
# This changes a lot, and isn't needed by anything onther than one screen inside CRG itself.
filter_keys=ScoreBoard\.Twitter\.
